console.log("3) Descubra a lógica e complete o próximo elemento:")
console.log(" ")
console.log("a) 1, 3, 5, 7, ___")
console.log("b) 2, 4, 8, 16, 32, 64, ____")
console.log("c) 0, 1, 4, 9, 16, 25, 36, ____")
console.log("d) 4, 16, 36, 64, ____")
console.log("e) 1, 1, 2, 3, 5, 8, ____")
console.log("f) 2,10, 12, 16, 17, 18, 19, ____")
console.log(" ")
console.log("Respoastas abaixo: ")

console.log("a) A lógica aqui é aumentar de 2 em 2. Portanto, o próximo número é 9.")
console.log("b) Cada número é multiplicado por 2 para obter o próximo número. Assim, o próximo número é 128.")
console.log("c) Esta sequência consiste nos quadrados dos números naturais consecutivos. O próximo número é 49, que é o quadrado de 7.")
console.log("d) Esses são os quadrados dos números pares consecutivos. O próximo número é 100, que é o quadrado de 10.")
console.log("e) Esta sequência segue a série de Fibonacci, onde cada número é a soma dos dois anteriores. Assim, o próximo número é 13 (5 + 8).")
console.log("f) Não consegui entender.. :( desculpe")