console.log("4) Você está em uma sala com três interruptores, cada um conectado a uma lâmpada em uma sala diferente. Você não pode ver as lâmpadas da sala em que está, mas pode ligar e desligar os interruptores quantas vezes quiser. Seu objetivo é descobrir qual interruptor controla qual lâmpada.")
console.log(" ")
console.log("Como você faria para descobrir, usando apenas duas idas até uma das salas das lâmpadas, qual interruptor controla cada lâmpada?")
console.log(" ")
console.log(" ")
console.log("RESPOSTA:")
console.log("Na primeira ida Ligue o primeiro interruptor e deixe-o ligado por alguns minutos, em seguida, desligue-o e ligue o segundo interruptor.")
console.log(" ")
console.log("Segunda ida entro na sala das lâmpadas a lâmpada que estiver acesa está conectada ao segundo interruptor.")
console.log("Toque nas lâmpadas desligadas para sentir qual delas está quente. a que estiver quente, está conectada ao primeiro interruptor a fria está conectada ao terceiro.")
